#!/usr/bin/python

############################################################################# 
#  BSD 3-Clause License
# 
#  Copyright (c) 2020, Noa Sendlhofer
#  All rights reserved.
# 
#  Redistribution and use in source and binary forms, with or without
#  modification, are permitted provided that the following conditions are met:
# 
#  1. Redistributions of source code must retain the above copyright notice, this
#     list of conditions and the following disclaimer.
# 
#  2. Redistributions in binary form must reproduce the above copyright notice,
#     this list of conditions and the following disclaimer in the documentation
#     and/or other materials provided with the distribution.
# 
#  3. Neither the name of the copyright holder nor the names of its
#     contributors may be used to endorse or promote products derived from
#     this software without specific prior written permission.
# 
#  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
#  AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
#  IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
#  DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
#  FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
#  DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
#  SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
#  CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
#  OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
#  OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
############################################################################# 

# Author: Noa Sendlhofer
# Desc:   Part of the NSRA Robot Vision stack. Handles the image ingest for callibration.

import cv2
import nsra_pyndi.finder as finder
import nsra_pyndi.receiver as receiver
import nsra_pyndi.lib as lib
import numpy as np
import rospkg
import threading

#rospack
rospack = rospkg.RosPack()
pack_path = rospack.get_path('nsra_robot_vision')

#config
PR = None
PL = None

try:
    fs = cv2.FileStorage(pack_path + "/config/cam_stereo.yml", cv2.FILE_STORAGE_READ)
    PR = fs.getNode("PR").mat()
    PL = fs.getNode("PL").mat()
except:
    print("Error no config file found!")
    quit()

if PR.any() == None or PL.any() == None:
    print("Error config file not valid!")
    quit()

rcam_name = "PC-NOA (TV0200110012)"
lcam_name = "PC-NOA (TV0200110013)"

criteria = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 30, 0.001)

origin_img = np.array([[0.0,0.0],
                       [0.0,0.0]])
origin_vec = np.array([0.0,0.0,0.0])


class Camera():
    def __init__(self, camera):
        find = finder.create_ndi_finder()
        NDIsources = find.get_sources()
        self.cam_source = None
        elapsed_time = 0.0
        print("Looking for cameras")
        while len(NDIsources) < 2:
            if elapsed_time >= 5.0:
                print("Timeout - Not all cameras detected!")
                quit()
            NDIsources = find.get_sources()
            elapsed_time += 1
        for i in NDIsources:
            if i.name == camera:
                self.cam_source = i
                break
        if self.cam_source == None:
            print("Detected cameras don't match with the input names")
            quit()
        else:
            self.camera = receiver.create_receiver(self.cam_source)
            print("Camera " + self.cam_source.name + " initialized")
    
    def get_frame(self):
        return self.camera.read()

    def get_name(self):
        return self.cam_source.name

right_cam = Camera(rcam_name)
left_cam = Camera(lcam_name)

def callibrate(img):
    global origin_img
    global origin_vec

    for i in range(2):
        gray = cv2.cvtColor(img[i], cv2.COLOR_BGR2GRAY)
        ret, corners = cv2.findChessboardCorners(gray, (6,9), None)
        if ret == True:
            corners2 = cv2.cornerSubPix(gray, corners, (11,11), (-1,-1), criteria)
            origin_img[i,0] = corners2[0,0,0] 
            origin_img[i,1] = corners2[0,0,1]
    
    p_4d = cv2.triangulatePoints(PR, PL, origin_img[0,:], origin_img[1,:])

    origin_vec = np.array([p_4d[0] / p_4d[3],
                           p_4d[1] / p_4d[3],
                           p_4d[2] / p_4d[3]])

while(True):
    img_left = left_cam.get_frame()
    img_right = right_cam.get_frame()

    if img_left is not Null and img_right is not Null:

        frame_l = cv2.resize(img_left, (1080, 720))
        frame_r = cv2.resize(img_right, (1080, 720))
        frame_l = cv2.flip(frame_l, 1)
        frame_r = cv2.flip(frame_r, 1)

        cv2.putText(frame_l, left_cam.get_name,(0,30),cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 0, 255), 1)
        cv2.putText(frame_r, right_cam.get_name,(0,30),cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 0, 255), 1)

        frame_r = cv2.circle(frame_r, (int(round(origin_img[0,0])), int(round(origin_img[0,1]))), radius=5, color=(0, 0, 255), thickness=-1)
        frame_l = cv2.circle(frame_l, (int(round(origin_img[1,0])), int(round(origin_img[1,1]))), radius=5, color=(0, 0, 255), thickness=-1)

        output_img = np.concatenate((frame_l, frame_r), axis=1)

        cv2.imshow('left and right camera', output_img)

    key = cv2.waitKey(50)
    if key == 27:
        print("User Quit")
        break
    if key == 10:
        callibrate([img_right, img_left])

cv2.destroyAllWindows()     
