// Generated by gencpp from file nsra_odrive_interface/nsra_control_step.msg
// DO NOT EDIT!


#ifndef NSRA_ODRIVE_INTERFACE_MESSAGE_NSRA_CONTROL_STEP_H
#define NSRA_ODRIVE_INTERFACE_MESSAGE_NSRA_CONTROL_STEP_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace nsra_odrive_interface
{
template <class ContainerAllocator>
struct nsra_control_step_
{
  typedef nsra_control_step_<ContainerAllocator> Type;

  nsra_control_step_()
    : axis1(0)
    , axis2(0)
    , axis3(0)
    , axis4(0)
    , axis5(0)
    , axis6(0)  {
    }
  nsra_control_step_(const ContainerAllocator& _alloc)
    : axis1(0)
    , axis2(0)
    , axis3(0)
    , axis4(0)
    , axis5(0)
    , axis6(0)  {
  (void)_alloc;
    }



   typedef int32_t _axis1_type;
  _axis1_type axis1;

   typedef int32_t _axis2_type;
  _axis2_type axis2;

   typedef int32_t _axis3_type;
  _axis3_type axis3;

   typedef int32_t _axis4_type;
  _axis4_type axis4;

   typedef int32_t _axis5_type;
  _axis5_type axis5;

   typedef int32_t _axis6_type;
  _axis6_type axis6;





  typedef boost::shared_ptr< ::nsra_odrive_interface::nsra_control_step_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::nsra_odrive_interface::nsra_control_step_<ContainerAllocator> const> ConstPtr;

}; // struct nsra_control_step_

typedef ::nsra_odrive_interface::nsra_control_step_<std::allocator<void> > nsra_control_step;

typedef boost::shared_ptr< ::nsra_odrive_interface::nsra_control_step > nsra_control_stepPtr;
typedef boost::shared_ptr< ::nsra_odrive_interface::nsra_control_step const> nsra_control_stepConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::nsra_odrive_interface::nsra_control_step_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::nsra_odrive_interface::nsra_control_step_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::nsra_odrive_interface::nsra_control_step_<ContainerAllocator1> & lhs, const ::nsra_odrive_interface::nsra_control_step_<ContainerAllocator2> & rhs)
{
  return lhs.axis1 == rhs.axis1 &&
    lhs.axis2 == rhs.axis2 &&
    lhs.axis3 == rhs.axis3 &&
    lhs.axis4 == rhs.axis4 &&
    lhs.axis5 == rhs.axis5 &&
    lhs.axis6 == rhs.axis6;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::nsra_odrive_interface::nsra_control_step_<ContainerAllocator1> & lhs, const ::nsra_odrive_interface::nsra_control_step_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace nsra_odrive_interface

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::nsra_odrive_interface::nsra_control_step_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nsra_odrive_interface::nsra_control_step_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::nsra_odrive_interface::nsra_control_step_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::nsra_odrive_interface::nsra_control_step_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nsra_odrive_interface::nsra_control_step_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nsra_odrive_interface::nsra_control_step_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::nsra_odrive_interface::nsra_control_step_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8d76cae6683f63e0ae2877b8fbfdf1d6";
  }

  static const char* value(const ::nsra_odrive_interface::nsra_control_step_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8d76cae6683f63e0ULL;
  static const uint64_t static_value2 = 0xae2877b8fbfdf1d6ULL;
};

template<class ContainerAllocator>
struct DataType< ::nsra_odrive_interface::nsra_control_step_<ContainerAllocator> >
{
  static const char* value()
  {
    return "nsra_odrive_interface/nsra_control_step";
  }

  static const char* value(const ::nsra_odrive_interface::nsra_control_step_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::nsra_odrive_interface::nsra_control_step_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 axis1\n"
"int32 axis2\n"
"int32 axis3\n"
"int32 axis4\n"
"int32 axis5\n"
"int32 axis6\n"
;
  }

  static const char* value(const ::nsra_odrive_interface::nsra_control_step_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::nsra_odrive_interface::nsra_control_step_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.axis1);
      stream.next(m.axis2);
      stream.next(m.axis3);
      stream.next(m.axis4);
      stream.next(m.axis5);
      stream.next(m.axis6);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct nsra_control_step_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::nsra_odrive_interface::nsra_control_step_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::nsra_odrive_interface::nsra_control_step_<ContainerAllocator>& v)
  {
    s << indent << "axis1: ";
    Printer<int32_t>::stream(s, indent + "  ", v.axis1);
    s << indent << "axis2: ";
    Printer<int32_t>::stream(s, indent + "  ", v.axis2);
    s << indent << "axis3: ";
    Printer<int32_t>::stream(s, indent + "  ", v.axis3);
    s << indent << "axis4: ";
    Printer<int32_t>::stream(s, indent + "  ", v.axis4);
    s << indent << "axis5: ";
    Printer<int32_t>::stream(s, indent + "  ", v.axis5);
    s << indent << "axis6: ";
    Printer<int32_t>::stream(s, indent + "  ", v.axis6);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NSRA_ODRIVE_INTERFACE_MESSAGE_NSRA_CONTROL_STEP_H
