#!/usr/bin/python3

############################################################################# 
#  BSD 3-Clause License
# 
#  Copyright (c) 2020, Noa Sendlhofer
#  All rights reserved.
# 
#  Redistribution and use in source and binary forms, with or without
#  modification, are permitted provided that the following conditions are met:
# 
#  1. Redistributions of source code must retain the above copyright notice, this
#     list of conditions and the following disclaimer.
# 
#  2. Redistributions in binary form must reproduce the above copyright notice,
#     this list of conditions and the following disclaimer in the documentation
#     and/or other materials provided with the distribution.
# 
#  3. Neither the name of the copyright holder nor the names of its
#     contributors may be used to endorse or promote products derived from
#     this software without specific prior written permission.
# 
#  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
#  AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
#  IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
#  DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
#  FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
#  DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
#  SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
#  CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
#  OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
#  OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
############################################################################# 

# Author: Noa Sendlhofer
# Desc:   Part of the NSRA Robot Vision stack. Stereo camera test program using an NDI source.
# 01.01.2021 - Stereo camera works! :)

import cv2
import nsra_pyndi.finder as finder
import nsra_pyndi.receiver as receiver
import nsra_pyndi.lib as lib
import subprocess as sp
import numpy as np
import math
import rospkg
import threading

#rospack
rospack = rospkg.RosPack()
pack_path = rospack.get_path('nsra_robot_vision')

#config
#Projection
PR = None
PL = None
#Intrinsics
KR = None
KL = None
#Distortion
DR = None
DL = None
#Rotation
RR = None
RL = None

try:
    fs = cv2.FileStorage(pack_path + "/config/cam_stereo.yml", cv2.FILE_STORAGE_READ)
    PR = fs.getNode("PR").mat()
    PL = fs.getNode("PL").mat()
    KR = fs.getNode("KR").mat()
    KL = fs.getNode("KL").mat()
    DR = fs.getNode("DR").mat()
    DL = fs.getNode("DL").mat()
    RR = fs.getNode("RR").mat()
    RL = fs.getNode("RL").mat()
except:
    print("Error no config file found!")
    quit()

if PR.any() == None or PL.any() == None:
    print("Error config file not valid!")
    quit()

try:
    chessImg = cv2.imread(pack_path + "/images/left1.jpg")
    imsize = (chessImg.shape[1], chessImg.shape[0])
except:
    print("Error no valid image found in the /image folder!")
    quit()

# initUndistortRectifyMap 
Left_Stereo_Map= cv2.initUndistortRectifyMap(KL, DL, RL, PL,
                                             imsize, cv2.CV_16SC2)
Right_Stereo_Map= cv2.initUndistortRectifyMap(KR, DR, RR, PR,
                                              imsize, cv2.CV_16SC2)

#temporary! - NDI stream names
rcam_name = "PC-NOA (TV0200110012)"
lcam_name = "PC-NOA (TV0200110013)"

#CBC detection
criteria = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 30, 0.001)

#World origin of cameras relative to the robot
origin_img = np.array([[0.0,0.0],
                       [0.0,0.0]])
origin_vec = np.array([0.0,0.0,0.0])

#NDI camera class
class Camera():
    def __init__(self, camera):
        find = finder.create_ndi_finder()
        NDIsources = find.get_sources()
        self.cam_source = None
        elapsed_time = 0.0
        while len(NDIsources) < 2:
            print("Looking for cameras")
            if elapsed_time >= 5.0:
                print("Timeout - Not all cameras detected!")
                quit()
            NDIsources = find.get_sources()
            elapsed_time += 1
        for i in NDIsources:
            if i.name == camera:
                self.cam_source = i
                break
        if self.cam_source == None:
            print("Detected cameras don't match with the input names")
            quit()
        else:
            self.camera = receiver.create_receiver(self.cam_source)
            print("Camera " + self.cam_source.name + " initialized")
    
    def get_frame(self):
        return self.camera.read()

    def get_name(self):
        return self.cam_source.name

#Create camera instances
right_cam = Camera(rcam_name)
left_cam = Camera(lcam_name)

rtmp_url = 'rtmp://192.168.1.174:1935/app/live'

sizeStr = str(2160) + \
    'x' + str(720)

print("------------------- STR: " + sizeStr)
command = ['ffmpeg',
           '-y',
           '-f', 'rawvideo',
           '-vcodec', 'rawvideo',
           '-pix_fmt', 'bgr24',
           '-s', sizeStr,
           '-r', str(30),
           '-i', '-',
           '-c:v', 'libx264',
           '-pix_fmt', 'yuv420p',
           '-preset', 'ultrafast',
           '-f', 'flv',
           rtmp_url]

process = sp.Popen(command, stdin=sp.PIPE)

#Calculate translation vector from cameras to world origin
def callibrate(img):
    global origin_img
    global origin_vec

    for i in range(2):
        gray = cv2.cvtColor(img[i], cv2.COLOR_BGR2GRAY)
        ret, corners = cv2.findChessboardCorners(gray, (6,9), None)
        if ret == True:
            corners2 = cv2.cornerSubPix(gray, corners, (11,11), (-1,-1), criteria)
            origin_img[i,0] = corners2[0,0,0]
            origin_img[i,1] = corners2[0,0,1]
    
    p_4d = cv2.triangulatePoints(PR, PL, origin_img[0,:], origin_img[1,:])

    origin_vec = np.array([p_4d[0] / p_4d[3],
                           p_4d[1] / p_4d[3],
                           p_4d[2] / p_4d[3]])
    print("origin_vec: ")
    print(origin_vec)

#Calculate distance of point relative to the world origin
def detect(img):
    pnts_img = np.array([[0.0,0.0],
                         [0.0,0.0],
                         [0.0,0.0],
                         [0.0,0.0]])
    for i in range(2):
        gray = cv2.cvtColor(img[i], cv2.COLOR_BGR2GRAY)
        ret, corners = cv2.findChessboardCorners(gray, (6,9), None)
        if ret == True:
            corners2 = cv2.cornerSubPix(gray, corners, (11,11), (-1,-1), criteria)
            pnts_img[i,0] = corners2[0,0,0]
            pnts_img[i,1] = corners2[0,0,1]
            pnts_img[i+2,0] = corners2[48,0,0]
            pnts_img[i+2,1] = corners2[48,0,1]
    
    p_4d_1 = cv2.triangulatePoints(PR, PL, pnts_img[0,:], pnts_img[1,:])
    p_4d_2 = cv2.triangulatePoints(PR, PL, pnts_img[2,:], pnts_img[3,:])

    dist_vec_pnt1 = np.array([p_4d_1[0] / p_4d_1[3] - origin_vec[0],
                              p_4d_1[1] / p_4d_1[3] - origin_vec[1],
                              p_4d_1[2] / p_4d_1[3] - origin_vec[2]])
    
    dist_vec_pnt2 = np.array([p_4d_2[0] / p_4d_2[3] - origin_vec[0],
                              p_4d_2[1] / p_4d_2[3] - origin_vec[1],
                              p_4d_2[2] / p_4d_2[3] - origin_vec[2]])
    
    pnt_dist_vec = np.subtract(dist_vec_pnt1, dist_vec_pnt2)

    print("---------------")
    print("Distance points: " + str(math.sqrt(pnt_dist_vec[0]**2 + pnt_dist_vec[1]**2 + pnt_dist_vec[2]**2)))
    print("Distance vector origin: ")
    print(dist_vec_pnt1)
    print("Distance origin: " + str(math.sqrt(dist_vec_pnt1[0]**2 + dist_vec_pnt1[1]**2 + dist_vec_pnt1[2]**2)))
    print("---------------")

while(True):
    #Get next image from cameras
    img_left = left_cam.get_frame()
    img_right = right_cam.get_frame()

    #Undistort rectify images
    img_left = cv2.remap(img_left,Left_Stereo_Map[0],Left_Stereo_Map[1], cv2.INTER_LANCZOS4, cv2.BORDER_CONSTANT, 0)
    img_right = cv2.remap(img_right,Right_Stereo_Map[0],Right_Stereo_Map[1], cv2.INTER_LANCZOS4, cv2.BORDER_CONSTANT, 0)

    #Draw world origin
    frame_r = cv2.circle(img_right, (int(round(origin_img[0,0])), int(round(origin_img[0,1]))), radius=5, color=(0, 0, 255), thickness=-1)
    frame_l = cv2.circle(img_left, (int(round(origin_img[1,0])), int(round(origin_img[1,1]))), radius=5, color=(0, 0, 255), thickness=-1)

    #Resize for imshow
    frame_l = cv2.resize(frame_l, (1080, 720))
    frame_r = cv2.resize(frame_r, (1080, 720))

    #Draw horizontal lines
    for line in range(0, int(frame_r.shape[0]/20)):
        frame_l[line*20,:] = (0,255,0,0)
        frame_r[line*20,:] = (0,255,0,0)

    #Concatenate left and right image
    output_img = np.concatenate((frame_l, frame_r), axis=1)

    #Show concentated frame
    #cv2.imshow('left and right camera', output_img)
    process.stdin.write(output_img.tobytes())

    #Wait for user input
    key = cv2.waitKey(50)
    if key == 27:
        print("User Quit")
        break
    elif key == 13:
        print("Callibrate camera origin")
        callibrate([img_right, img_left])
    elif key == 32:
        detect([img_right, img_left])

cv2.destroyAllWindows()