#!/usr/bin/python
import cv2
import numpy as np
import scipy as sp
import scipy.interpolate
import rospy
from std_msgs.msg import String
import sys
import time
import multiprocessing as mp
import math
from nsra_odrive_interface.msg import obj_det
from nsra_odrive_interface.srv import *

origin = np.array([0,0])
x_vec = np.array([0,0])
rotation = 0.0
scaling_factor = 1.0
dist_factor = 277.0/166.0
offset_factor = 1.0

scaling_factor_offset = 1.0
table_hight = 740
camera_hight = 1360

camera_distance = 0

pts_center = np.array([])
pts_top_left = np.array([])
pts_botton_right = np.array([])

t=np.array([702,584,505,430,389,344,316,274,241,213,192 ,172, 158, 145, 140])
v=np.array([273,327,378,445,490,555,602,700,800,900,1000,1100,1200,1300,1350])

class camera():

    def __init__(self,rtsp_url):        
        #load pipe for data transmittion to the process
        self.parent_conn, child_conn = mp.Pipe()
        #load process
        self.p = mp.Process(target=self.update, args=(child_conn,rtsp_url))        
        #start process
        self.p.daemon = True
        self.p.start()

    def end(self):
        #send closure request to process

        self.parent_conn.send(2)

    def update(self,conn,rtsp_url):
        #load cam into seperate process

        print("Cam Loading...")
        cap = cv2.VideoCapture(rtsp_url,cv2.CAP_FFMPEG)   
        print("Cam Loaded...")
        run = True

        while run:

            #grab frames from the buffer
            cap.grab()

            #recieve input data
            rec_dat = conn.recv()


            if rec_dat == 1:
                #if frame requested
                ret,frame = cap.read()
                conn.send(frame)

            elif rec_dat ==2:
                #if close requested
                cap.release()
                run = False

        print("Camera Connection Closed")        
        conn.close()

    def get_frame(self,resize=None):
        ###used to grab frames from the cam connection process

        ##[resize] param : % of size reduction or increase i.e 0.65 for 35% reduction  or 1.5 for a 50% increase

        #send request
        self.parent_conn.send(1)
        frame = self.parent_conn.recv()

        #reset request 
        self.parent_conn.send(0)

        #resize if needed
        if resize == None:            
            return frame
        else:
            return self.rescale_frame(frame,resize)

    def rescale_frame(self,frame, percent=65):

        return cv2.resize(frame,None,fx=percent,fy=percent) 

cam = camera(str(sys.argv[1]))

def find_nearest(array, value):
    array = np.asarray(array)
    idx = (np.abs(array - value)).argmin()
    return idx

def find_cb_corners():
    global cam
    global origin
    global x_vec
    global rotation
    global scaling_factor
    global t
    global v
    global dist_factor
    global camera_distance
    global table_hight
    global camera_hight
    global scaling_factor_offset
    frame = cam.get_frame(1)
    blur_frame = cv2.GaussianBlur(frame, (5,5), 1)
    retval, corners = cv2.findChessboardCorners(blur_frame, (6,9), flags=cv2.CALIB_CB_FAST_CHECK)
    if retval:
        r,g,b=cv2.split(blur_frame)
        criteria = (cv2.TermCriteria_EPS + cv2.TermCriteria_MAX_ITER, 30, 0.1)
        cv2.cornerSubPix(r, corners, (11,11), (-1,-1), criteria)
        cv2.drawChessboardCorners(blur_frame, (6,9), corners, retval)
        cv2.imwrite("ref_point.jpg", blur_frame)
        #print(corners)

        origin = [corners[0,0,0], corners[0,0,1]]
        x_vec = [corners[5,0,0] - corners[0,0,0], corners[5,0,1] - corners[0,0,1]]
        #print(str(x_vec[0]) + " / " + str(x_vec[1]))
        A = math.atan(x_vec[0]/x_vec[1])
        #A = math.degrees(A)
        rotation = A
        

        cb_dist_vec = np.array([corners[48,0,0] - corners[0,0,0], corners[48,0,1] - corners[0,0,1]])
        cb_dist = int(np.linalg.norm(cb_dist_vec))

        scaling_factor = 277/np.linalg.norm(cb_dist_vec)*scaling_factor_offset

        tnew=np.arange(start=702,stop=140,step=-1)
        fvcubic=sp.interpolate.interp1d(t,v,kind='cubic')
        vcubic=fvcubic(tnew)
        dist = int(np.round(vcubic[702-cb_dist],0)*dist_factor)

        camera_distance = int(math.sqrt(dist**2 - (camera_hight-table_hight)**2))

        print(dist_factor)
        print("")
        print("Calibration successful!")
        print("origin: " + str(origin))
        print("x_vec: " + str(x_vec))
        print("rotation: " + str(rotation) + " radians")
        print("scaling factor: " + str(scaling_factor))
        print("Camera distance: " + str(camera_distance))
        print("")   
    else:
        print("No corners detected!")

def JI_Callback(data):
    global pts_center
    global pts_top_left
    global pts_botton_right
    if len(data.Center_x) != 0:
        center = np.array([[data.Center_x[0], data.Center_y[0]]])
        pts_top_left = np.array([[data.Top[0], data.Left[0]]])
        pts_botton_right = np.array([[data.Bottom[0], data.Right[0]]])
        for i in range(len(data.Center_x)-1):
            b = np.array([[data.Center_x[i+1], data.Center_y[i+1]]])
            c = np.array([[data.Top[i+1], data.Left[i+1]]])
            d = np.array([[data.Bottom[i+1], data.Right[i+1]]])
            center = np.concatenate((center, b), axis=0)
            pts_top_left = np.concatenate((pts_top_left, c), axis=0)
            pts_botton_right = np.concatenate((pts_botton_right, d), axis=0)
        pts_center = center

rospy.init_node('bd_front_view')
rospy.Subscriber('bottle_detection', obj_det, JI_Callback)

rospy.wait_for_service('bd_y_coords')

bd_y_coords = rospy.ServiceProxy('bd_y_coords', bd_coords)

while True:
    frame = cam.get_frame(1)

    resp = bd_y_coords(0)

    x_coords = np.array([])
    y_coords = np.array([])

    x_coords = resp.x_coords
    y_coords = resp.y_coords

    if len(x_coords) != 0:
        for i in range(len(x_coords)):
            of_f = 1.0
            try:
                of_f = 1 - 1/(camera_distance/y_coords[i]*scaling_factor)
                print(str(1 - 1/(camera_distance/y_coords[i]*scaling_factor)))
            except:
                print(0)
            cv2.circle(frame,(int(x_coords[i]*scaling_factor*of_f + origin[0]), 270), 5, (0,255,0), -1)

    if len(pts_center) != 0:
        for i in range(len(pts_center)):
            cv2.circle(frame,(int(pts_center[i,0]), 270), 5, (0,0,255), -1)
            cv2.rectangle(frame, (int(pts_top_left[i,0]), int(pts_top_left[i,1])), (int(pts_botton_right[i,0]), int(pts_botton_right[i,1])), (255,0,0), 3)

    cv2.imshow("Front view", frame)

    key = cv2.waitKey(1)
    if key == 27:
        break
    if key == 10:
        find_cb_corners()