#!/usr/bin/python
import cv2
import numpy as np
import rospy
from std_msgs.msg import String
import sys
import time
import multiprocessing as mp
import math
from nsra_odrive_interface.msg import obj_det
from nsra_odrive_interface.srv import *

origin = np.array([0,0])
x_vec = np.array([0,0])
rotation = 0.0
scaling_factor = 1.0

pts_ji = np.array([])
pts_tv = np.array([])

class camera():

    def __init__(self,rtsp_url):        
        #load pipe for data transmittion to the process
        self.parent_conn, child_conn = mp.Pipe()
        #load process
        self.p = mp.Process(target=self.update, args=(child_conn,rtsp_url))        
        #start process
        self.p.daemon = True
        self.p.start()

    def end(self):
        #send closure request to process

        self.parent_conn.send(2)

    def update(self,conn,rtsp_url):
        #load cam into seperate process

        print("Cam Loading...")
        cap = cv2.VideoCapture(rtsp_url,cv2.CAP_FFMPEG)   
        print("Cam Loaded...")
        run = True

        while run:

            #grab frames from the buffer
            cap.grab()

            #recieve input data
            rec_dat = conn.recv()


            if rec_dat == 1:
                #if frame requested
                ret,frame = cap.read()
                conn.send(frame)

            elif rec_dat ==2:
                #if close requested
                cap.release()
                run = False

        print("Camera Connection Closed")        
        conn.close()

    def get_frame(self,resize=None):
        ###used to grab frames from the cam connection process

        ##[resize] param : % of size reduction or increase i.e 0.65 for 35% reduction  or 1.5 for a 50% increase

        #send request
        self.parent_conn.send(1)
        frame = self.parent_conn.recv()

        #reset request 
        self.parent_conn.send(0)

        #resize if needed
        if resize == None:            
            return frame
        else:
            return self.rescale_frame(frame,resize)

    def rescale_frame(self,frame, percent=65):

        return cv2.resize(frame,None,fx=percent,fy=percent) 

cam = camera(str(sys.argv[1]))

def find_cb_corners():
    global cam
    global origin
    global x_vec
    global rotation
    global scaling_factor
    frame = cam.get_frame(1)
    blur_frame = cv2.GaussianBlur(frame, (5,5), 1)
    retval, corners = cv2.findChessboardCorners(blur_frame, (6,9), flags=cv2.CALIB_CB_FAST_CHECK)
    if retval:
        r,g,b=cv2.split(blur_frame)
        criteria = (cv2.TermCriteria_EPS + cv2.TermCriteria_MAX_ITER, 30, 0.1)
        cv2.cornerSubPix(r, corners, (11,11), (-1,-1), criteria)
        cv2.drawChessboardCorners(blur_frame, (6,9), corners, retval)
        cv2.imwrite("ref_point.jpg", blur_frame)
        #print(corners)

        origin = [corners[0,0,0], corners[0,0,1]]
        x_vec = [corners[5,0,0] - corners[0,0,0], corners[5,0,1] - corners[0,0,1]]
        #print(str(x_vec[0]) + " / " + str(x_vec[1]))
        A = math.atan(x_vec[0]/x_vec[1])
        #A = math.degrees(A)
        rotation = A
        scaling_factor = 172/np.linalg.norm(x_vec)
        print("")
        print("Calibration successful!")
        print("origin: " + str(origin))
        print("x_vec: " + str(x_vec))
        print("rotation: " + str(rotation) + " radians")
        print("scaling factor: " + str(scaling_factor))
        print("")   
    else:
        print("No corners detected!")

def JI_Callback(data):
    global pts_center
    if len(data.Center_x) != 0:
        center = np.array([[data.Center_x[0], data.Center_y[0]]])
        for i in range(len(data.Center_x)-1):
            b = np.array([[data.Center_x[i+1], data.Center_y[i+1]]])
            center = np.concatenate((center, b), axis=0)
        pts_center = center

rospy.init_node('bd_front_view')
rospy.Subscriber('bottle_detection', obj_det, JI_Callback)

rospy.wait_for_service('bd_y_coords')

bd_y_coords = rospy.ServiceProxy('bd_y_coords', bd_coords)

while True:
    frame = cam.get_frame(1)

    x_coords, y_coords = bd_y_coords(0)

    if len(x_coords) != 0:
        for i in range(len(x_coords)):
            cv2.circle(frame,(int(x_coords[i]), int(y_coords[i])), 5, (0,255,0), -1)

    if len(pts_center) != 0:
        for i in range(len(pts_center)):
            cv2.circle(frame,(int(pts_center[i,0]), int(pts_center[i,1])), 5, (0,0,255), -1)

    cv2.imshow("Front view", frame)

    key = cv2.waitKey(1)
    if key == 27:
        break