#!/usr/bin/python
import cv2
import numpy as np
import rospy
from std_msgs.msg import String
import sys
import time
import multiprocessing as mp
from nsra_odrive_interface.srv import *

a = np.array([[ 5, 1 ,3], 
              [ 1, 1 ,1], 
              [ 1, 2 ,1]])

b = np.array([1, 2, 3])

print a.dot(b)

rl = 90
gl = 40
bl = 100
rh = 115
gh = 255
bh = 255

class camera():

    def __init__(self,rtsp_url):        
        #load pipe for data transmittion to the process
        self.parent_conn, child_conn = mp.Pipe()
        #load process
        self.p = mp.Process(target=self.update, args=(child_conn,rtsp_url))        
        #start process
        self.p.daemon = True
        self.p.start()

    def end(self):
        #send closure request to process

        self.parent_conn.send(2)

    def update(self,conn,rtsp_url):
        #load cam into seperate process

        print("Cam Loading...")
        cap = cv2.VideoCapture(rtsp_url,cv2.CAP_FFMPEG)   
        print("Cam Loaded...")
        run = True

        while run:

            #grab frames from the buffer
            cap.grab()

            #recieve input data
            rec_dat = conn.recv()


            if rec_dat == 1:
                #if frame requested
                ret,frame = cap.read()
                conn.send(frame)

            elif rec_dat ==2:
                #if close requested
                cap.release()
                run = False

        print("Camera Connection Closed")        
        conn.close()

    def get_frame(self,resize=None):
        ###used to grab frames from the cam connection process

        ##[resize] param : % of size reduction or increase i.e 0.65 for 35% reduction  or 1.5 for a 50% increase

        #send request
        self.parent_conn.send(1)
        frame = self.parent_conn.recv()

        #reset request 
        self.parent_conn.send(0)

        #resize if needed
        if resize == None:            
            return frame
        else:
            return self.rescale_frame(frame,resize)

    def rescale_frame(self,frame, percent=65):

        return cv2.resize(frame,None,fx=percent,fy=percent) 

cam = camera(str(sys.argv[1]))

def paramsChangeCallback(data):
    msg = str(data.data)
    sp_msg = msg.split("/")

    global rl
    global gl
    global bl
    global rh
    global gh
    global bh
    
    rl = int(sp_msg[0])
    gl = int(sp_msg[1])
    bl = int(sp_msg[2])
    rh = int(sp_msg[3])
    gh = int(sp_msg[4])
    bh = int(sp_msg[5])

def bd_y_coords(req):
    return coordsResponse(corner_x, corner_y)

rospy.init_node('bd_top_view')
rospy.Subscriber("bd_params", String, paramsChangeCallback)
s = rospy.Service('bd_y_coords', bd_coords, bd_y_coords)

params = cv2.SimpleBlobDetector_Params()

params.filterByArea = True
params.minArea = 20
params.maxArea = 10000

params.filterByCircularity = True
params.minCircularity = 0.1

params.filterByConvexity = True
params.minConvexity = 0.2

params.filterByInertia = True
params.minInertiaRatio = 0.1

detector = cv2.SimpleBlobDetector_create(params)

while True:
    frame = cam.get_frame(0.65)
    blur_frame = cv2.GaussianBlur(frame, (5,5), 1)
    hsv_frame = cv2.cvtColor(blur_frame, cv2.COLOR_BGR2HSV)

    low_red = np.array([rl,gl,bl])
    high_red = np.array([rh, gh, bh])
    red_mask = cv2.inRange(hsv_frame, low_red, high_red)

    red_mask = cv2.bitwise_not(red_mask)

    kernal = np.ones((10,10), np.uint8)
    red_mask = cv2.dilate(red_mask, kernal)

    keypoints = detector.detect(red_mask)

    x = np.array([])
    for i in len(keypoints):
        x = np.append(x, keypoints[i].pt[0])

    print(x)

    imgKeyPoints = cv2.drawKeypoints(red_mask, keypoints, np.array([]), (0,0,255), cv2.DRAW_MATCHES_FLAGS_DRAW_RICH_KEYPOINTS)

    cv2.imshow("Keypoints Left", imgKeyPoints)

    key = cv2.waitKey(1)
    if key == 27:
        break