#!/usr/bin/python
import cv2
import numpy as np
import rospy
from std_msgs.msg import String
import sys
import time
import multiprocessing as mp
from nsra_odrive_interface.srv import *
import math

rl = 90
gl = 40
bl = 100
rh = 115
gh = 255
bh = 255

offset_factor = 0.8/960

origin = np.array([0,0])
x_vec = np.array([0,0])
rotation = 0.0
scaling_factor = 1.0

x_coord = np.array([])
y_coord = np.array([])

class camera():

    def __init__(self,rtsp_url):        
        #load pipe for data transmittion to the process
        self.parent_conn, child_conn = mp.Pipe()
        #load process
        self.p = mp.Process(target=self.update, args=(child_conn,rtsp_url))        
        #start process
        self.p.daemon = True
        self.p.start()

    def end(self):
        #send closure request to process

        self.parent_conn.send(2)

    def update(self,conn,rtsp_url):
        #load cam into seperate process

        print("Cam Loading...")
        cap = cv2.VideoCapture(rtsp_url,cv2.CAP_FFMPEG)   
        print("Cam Loaded...")
        run = True

        while run:

            #grab frames from the buffer
            cap.grab()

            #recieve input data
            rec_dat = conn.recv()


            if rec_dat == 1:
                #if frame requested
                ret,frame = cap.read()
                conn.send(frame)

            elif rec_dat ==2:
                #if close requested
                cap.release()
                run = False

        print("Camera Connection Closed")        
        conn.close()

    def get_frame(self,resize=None):
        ###used to grab frames from the cam connection process

        ##[resize] param : % of size reduction or increase i.e 0.65 for 35% reduction  or 1.5 for a 50% increase

        #send request
        self.parent_conn.send(1)
        frame = self.parent_conn.recv()

        #reset request 
        self.parent_conn.send(0)

        #resize if needed
        if resize == None:            
            return frame
        else:
            return self.rescale_frame(frame,resize)

    def rescale_frame(self,frame, percent=65):

        return cv2.resize(frame,None,fx=percent,fy=percent) 

cam = camera(str(sys.argv[1]))

def rot_pts(pts):
    global rotation
    a = np.array([[math.cos(rotation), math.sin(rotation)],
                  [-math.sin(rotation), math.cos(rotation)]])
    for i in range(len(pts)):
        pts[i,:] = a.dot(pts[i,:])
    return pts

def find_cb_corners():
    global cam
    global origin
    global x_vec
    global rotation
    global scaling_factor
    frame = cam.get_frame(0.65)
    blur_frame = cv2.GaussianBlur(frame, (5,5), 1)
    retval, corners = cv2.findChessboardCorners(blur_frame, (6,9), flags=cv2.CALIB_CB_FAST_CHECK)
    if retval:
        r,g,b=cv2.split(blur_frame)
        criteria = (cv2.TermCriteria_EPS + cv2.TermCriteria_MAX_ITER, 30, 0.1)
        cv2.cornerSubPix(r, corners, (11,11), (-1,-1), criteria)
        cv2.drawChessboardCorners(blur_frame, (6,9), corners, retval)
        #cv2.imwrite("ref_point.jpg", blur_frame)
        #print(corners)

        origin = [corners[0,0,0], corners[0,0,1]]
        x_vec = [corners[5,0,0] - corners[0,0,0], corners[5,0,1] - corners[0,0,1]]
        #print(str(x_vec[0]) + " / " + str(x_vec[1]))
        A = math.atan(x_vec[0]/x_vec[1])
        #A = math.degrees(A)
        rotation = A
        scaling_factor = 172/np.linalg.norm(x_vec)
        print("")
        print("Calibration successful!")
        print("origin: " + str(origin))
        print("x_vec: " + str(x_vec))
        print("rotation: " + str(rotation) + " radians")
        print("scaling factor: " + str(scaling_factor))
        print("")

    else:
        print("No corners detected!")

def find_nearest(array, value):
    array = np.asarray(array)
    idx = (np.abs(array - value)).argmin()
    return idx

def paramsChangeCallback(data):
    msg = str(data.data)
    sp_msg = msg.split("/")

    global rl
    global gl
    global bl
    global rh
    global gh
    global bh
    
    rl = int(sp_msg[0])
    gl = int(sp_msg[1])
    bl = int(sp_msg[2])
    rh = int(sp_msg[3])
    gh = int(sp_msg[4])
    bh = int(sp_msg[5])

def bd_y_coords(req):
    global x_coord
    global y_coord
    global origin
    global scaling_factor
    global offset_factor
    print(y_coord)
    pts_array = np.array([[origin[0] - x_coord[0], y_coord[0] - origin[1]]])
    for i in range(len(x_coord)-1):
        b = np.array([[origin[0] - x_coord[i+1], y_coord[i+1] - origin[1]]])
        pts_array = np.concatenate((pts_array, b), axis=0)
    print("Pts: " + str(pts_array))
    rotated_pts = rot_pts(pts_array)
    print("rot_pts: " + str(rotated_pts))

    x_coord_rot = rotated_pts[:,0]
    y_coord_rot = rotated_pts[:,1]

    idx = find_nearest(y_coord_rot*scaling_factor, req.x_coord)

    #print(np.linalg.norm(rotated_pts[0,:])*scaling_factor)

    ofst_corr_pt = x_coord_rot[idx]-(origin[0] - x_coord_rot[idx])*offset_factor

    return bd_coordsResponse(ofst_corr_pt)

rospy.init_node('bd_top_view')
rospy.Subscriber("bd_params", String, paramsChangeCallback)
s = rospy.Service('bd_y_coords', bd_coords, bd_y_coords)

params = cv2.SimpleBlobDetector_Params()

params.filterByArea = True
params.minArea = 100
params.maxArea = 10000

params.filterByCircularity = True
params.minCircularity = 0.1

params.filterByConvexity = True
params.minConvexity = 0.2

params.filterByInertia = True
params.minInertiaRatio = 0.1

detector = cv2.SimpleBlobDetector_create(params)

while True:
    frame = cam.get_frame(1)
    blur_frame = cv2.GaussianBlur(frame, (5,5), 1)
    hsv_frame = cv2.cvtColor(blur_frame, cv2.COLOR_BGR2HSV)

    low_red = np.array([rl,gl,bl])
    high_red = np.array([rh, gh, bh])
    red_mask = cv2.inRange(hsv_frame, low_red, high_red)

    red_mask = cv2.bitwise_not(red_mask)

    kernal = np.ones((10,10), np.uint8)
    red_mask = cv2.dilate(red_mask, kernal)

    keypoints = detector.detect(red_mask)

    x = np.array([])
    y = np.array([])
    for i in range(len(keypoints)):
        x = np.append(x, keypoints[i].pt[0])
        y = np.append(y, keypoints[i].pt[1])
    x_coord = x
    y_coord = y

    imgKeyPoints = cv2.drawKeypoints(red_mask, keypoints, np.array([]), (0,0,255), cv2.DRAW_MATCHES_FLAGS_DRAW_RICH_KEYPOINTS)

    cv2.imshow("Keypoints Left", imgKeyPoints)

    key = cv2.waitKey(1)
    if key == 27:
        break
    if key == 10:
        find_cb_corners()
        