#!/usr/bin/python

import cv2
import time
import multiprocessing as mp
import numpy as np
import rospkg
import yaml
import thread
import sys
import gxipy as gx
from PIL import 
from threading import Thread
import subprocess as sp

rospack = rospkg.RosPack()

q_r = Queue(maxsize=1)
q_l = Queue(maxsize=1)
m_gLiveFlag = 1
m_gProcessFlag = 1
killFlag = 1

def live_image(threadName, delay, cam_num):
    
    device_manager = gx.DeviceManager()
    dev_num, dev_info_list = device_manager.update_device_list()
    if dev_num == 0:
        print("Number of enumerated devices is 0")
        return

    if cam_num == 1:

        cam1 = device_manager.open_device_by_sn("TV0200110013")

        if cam1.PixelColorFilter.is_implemented() == False:
            print("This sample does not support mono camera.")
            cam1.close_device()
            return

        cam1.TriggerMode.set(gx.GxSwitchEntry.OFF)

        cam1.ExposureTime.set(30000.0)

        cam1.Gain.set(20.0)

        cam1.BalanceWhiteAuto.set(1)

        if cam1.GammaParam.is_readable():
            gamma_value = cam1.GammaParam.get()
            gamma_lut = gx.Utility.get_gamma_lut(gamma_value)
        else:
            gamma_lut = None
        if cam1.ContrastParam.is_readable():
            contrast_value = cam1.ContrastParam.get()
            contrast_lut = gx.Utility.get_contrast_lut(contrast_value)
        else:
            contrast_lut = None
        if cam1.ColorCorrectionParam.is_readable():
            color_correction_param = cam1.ColorCorrectionParam.get()
        else:
            color_correction_param = 0

        cam1.data_stream[0].set_acquisition_buffer_number(1)
        cam1.stream_on()

    elif cam_num == 2:

        cam = device_manager.open_device_by_sn("TV0200110012")

        if cam.PixelColorFilter.is_implemented() == False:
            print("This sample does not support mono camera.")
            cam.close_device()
            return

        cam.TriggerMode.set(gx.GxSwitchEntry.OFF)

        cam.ExposureTime.set(30000.0)

        cam.Gain.set(20.0)

        cam.BalanceWhiteAuto.set(1)

        if cam.GammaParam.is_readable():
            gamma_value = cam.GammaParam.get()
            gamma_lut = gx.Utility.get_gamma_lut(gamma_value)
        else:
            gamma_lut = None
        if cam.ContrastParam.is_readable():
            contrast_value = cam.ContrastParam.get()
            contrast_lut = gx.Utility.get_contrast_lut(contrast_value)
        else:
            contrast_lut = None
        if cam.ColorCorrectionParam.is_readable():
            color_correction_param = cam.ColorCorrectionParam.get()
        else:
            color_correction_param = 0

        cam.data_stream[0].set_acquisition_buffer_number(1)
        cam.stream_on()
    
    else:
        print("Error device number")
        return

    while m_gLiveFlag:

        if cam_num == 1:

            raw_image_l = cam1.data_stream[0].get_image()

            if raw_image_l is None:
                print("Getting image failed.")
                continue

            if raw_image_l.get_status() == gx.GxFrameStatusList.INCOMPLETE:
                pass

            rgb_image_l = raw_image_l.convert("RGB")
            if rgb_image_l is None:
                continue

            numpy_image_l = rgb_image_l.get_numpy_array()
            if numpy_image_l is None:
                continue

            pimg_l = cv2.cvtColor(np.asarray(numpy_image_l),cv2.COLOR_BGR2RGB)

            drawing_bgr = cv2.cvtColor(pimg_l, cv2.COLOR_RGB2BGR)
            if q_l.qsize() == 0:
                q_l.put(drawing_bgr)

        elif cam_num == 2:

            raw_image_r = cam.data_stream[0].get_image()

            if raw_image_r is None:
                print("Getting image failed.")
                continue

            if raw_image_r.get_status() == gx.GxFrameStatusList.INCOMPLETE:
                pass

            rgb_image_r = raw_image_r.convert("RGB")
            if rgb_image_r is None:
                continue

            numpy_image_r = rgb_image_r.get_numpy_array()
            if numpy_image_r is None:
                continue

            pimg_r = cv2.cvtColor(np.asarray(numpy_image_r),cv2.COLOR_BGR2RGB)

            drawing_bgr = cv2.cvtColor(pimg_r, cv2.COLOR_RGB2BGR)
            if q_r.qsize() == 0:
                q_r.put(drawing_bgr) 

        else:
            print("Error device number")
            return 
        
        key = cv2.waitKey(1)
        if key == 27:
            break
    
    if cam_num == 1:
        cam.stream_off()
        cam.close_device()
    elif cam_num == 2:
        cam1.stream_off()
        cam1.close_device()

    cv2.destroyAllWindows()  

class camera():

    def __init__(self,rtsp_url):        
        #load pipe for data transmittion to the process
        self.parent_conn, child_conn = mp.Pipe()
        #load process
        self.p = mp.Process(target=self.update, args=(child_conn,rtsp_url))        
        #start process
        self.p.daemon = True
        self.p.start()

    def end(self):
        #send closure request to process

        self.parent_conn.send(2)

    def update(self,conn,rtsp_url):
        #load cam into seperate process

        print("Cam Loading...")
        cap = cv2.VideoCapture(rtsp_url,cv2.CAP_FFMPEG)   
        print("Cam Loaded...")
        run = True

        while run:

            #grab frames from the buffer
            cap.grab()

            #recieve input data
            rec_dat = conn.recv()


            if rec_dat == 1:
                #if frame requested
                ret,frame = cap.read()
                conn.send(frame)

            elif rec_dat ==2:
                #if close requested
                cap.release()
                run = False

        print("Camera Connection Closed")        
        conn.close()

    def get_frame(self,resize=None):
        ###used to grab frames from the cam connection process

        ##[resize] param : % of size reduction or increase i.e 0.65 for 35% reduction  or 1.5 for a 50% increase

        #send request
        self.parent_conn.send(1)
        frame = self.parent_conn.recv()

        #reset request 
        self.parent_conn.send(0)

        #resize if needed
        if resize == None:            
            return frame
        else:
            return self.rescale_frame(frame,resize)

    def rescale_frame(self,frame, percent=65):

        return cv2.resize(frame,None,fx=percent,fy=percent) 

def process_image( threadName, delay):

    while m_gProcessFlag == 1:
      cv2.waitKey(1)
      if q.qsize() > 0:
        pimg = q.get()
        process.stdin.write(pimg.tobytes())

cam_left = camera(str(sys.argv[1]))
cam_right = camera(str(sys.argv[2]))

criteria = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 30, 0.001)

objp = np.zeros((6*9,3), np.float32)
objp[:,:2] = np.mgrid[0:225:25,0:150:25].T.reshape(-1,2)

print(objp)

objpoints_left = [] 
objpoints_right = [] 

imgpoints_left = [] 
imgpoints_right = [] 

img_nb = int(sys.argv[3])

pack_path = rospack.get_path('nsra_robot_vision')

def findCBC_LEFT(img):
    image_name = pack_path + '/images/left' + str(img_nb + 1) + '.jpg'
    cv2.imwrite(image_name, img)
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    ret, corners = cv2.findChessboardCorners(gray, (6,9), None)
    if ret == True:
        objpoints_left.append(objp)
        corners2 = cv2.cornerSubPix(gray,corners,(11,11),(-1,-1),criteria)
        imgpoints_left.append(corners2)
    else:
        print("No corners detected in the left image!")     

def findCBC_RIGHT(img):
    image_name = pack_path + '/images/right' + str(img_nb + 1) + '.jpg'
    cv2.imwrite(image_name, img)
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    ret, corners = cv2.findChessboardCorners(gray, (6,9), None)
    if ret == True:
        objpoints_right.append(objp)
        corners2 = cv2.cornerSubPix(gray,corners,(11,11),(-1,-1),criteria)
        imgpoints_right.append(corners2)
    else:
        print("No corners detected in the right image!")

t1 = Thread(target=live_image, args=("live_image", 5, 1))
t1.start()

t2 = Thread(target=live_image, args=("live_image", 5, 2))
t2.start()

while(1):
    img_left = q_l.get()
    img_right = q_r.get()

    cv2.imshow('left camera', img_left)
    cv2.imshow('right camera', img_right)

    key = cv2.waitKey(1)

    if key == 27:
        break
    elif (key == 10) and (img_nb > 0):
        print("Remaining Images: " + str(img_nb))
        img_nb -= 1
        
        thread.start_new_thread(findCBC_LEFT,(img_left,))
        thread.start_new_thread(findCBC_RIGHT,(img_right,))
    elif(img_nb == 0):
        ret1, mtx1, dist1, rvecs1, tvecs1 = cv2.calibrateCamera(objpoints_left, imgpoints_left, (1920,1080), None, None)
        print("RMS1: " + str(ret1))
        #data1 = {'K': np.asarray(mtx1).tolist(),
        #        'D': np.asarray(dist1).tolist()}

        #with open(pack_path + "/config/intrinsics_left.yaml", "w") as f1:
        #    yaml.dump(data1, f1)

        fsl = cv2.FileStorage(pack_path + "/config/intrinsics_left.yml", flags=1)
        fsl.write(name='K', val=mtx1)
        fsl.write(name='D', val=dist1)
        fsl.release()

        ret2, mtx2, dist2, rvecs2, tvecs2 = cv2.calibrateCamera(objpoints_right, imgpoints_right, (1920,1080), None, None)
        print("RMS2: " + str(ret2)) 
        #data2 = {'K': np.asarray(mtx2).tolist(),
        #        'D': np.asarray(dist2).tolist()}

        #with open(pack_path + "/config/intrinsics_right.yaml", "w") as f2:
        #    yaml.dump(data2, f2)

        fsr = cv2.FileStorage(pack_path + "/config/intrinsics_right.yml", flags=1)
        fsr.write(name='K', val=mtx2)
        fsr.write(name='D', val=dist2)
        fsr.release()

        m_gLiveFlag = 0
        t1.join()
        t2.join()
        break
            
cv2.destroyAllWindows()     
