#!/usr/bin/env python3

from __future__ import print_function

import rospy
from std_msgs.msg import String
from std_msgs.msg import Float64
import odrive
from odrive.enums import *
import time
import math

from nsra_odrive_interface.srv import *

print("Connecting...")
odrv1 = odrive.find_any(serial_number="20573882304E")
print("Connected to ODrive 1")

def drive_pub6(data):

    print(data.data)
    
    print(odrv1.axis0.encoder.pos_estimate)


def axis_requested_state(req):
    print("Axis requested_state")

    if req.axis == 6:
        if req.requested_state == 0:
            odrv1.axis1.requested_state = AXIS_STATE_FULL_CALIBRATION_SEQUENCE
            while odrv1.axis1.current_state != AXIS_STATE_IDLE:
                time.sleep(0.1)
            odrv1.axis1.requested_state = AXIS_STATE_CLOSED_LOOP_CONTROL
        else:
            odrv1.axis1.requested_state = req.requested_state

    return requested_stateResponse(True)

rospy.init_node('odrive1_driver')

rospy.Subscriber("/nsra/drive_pub6", Float64, drive_pub6)

requested_state = rospy.Service('odrv1_requested_state', requested_state, axis_requested_state)

rospy.spin()
