#!/usr/bin/python
import cv2
import numpy as np

cap = cv2.VideoCapture("rtsp://192.168.1.171")

c_points = np.float32
i_points = np.float32([[0, 0, 0], [0, 130, 0], [130, 0, 0], [130, 130, 0]])

K = np.float64([[1.8196232063840237e+03, 0, 9.5950000000000000e+02],
                [0, 1.8196232063840237e+03, 5.3950000000000000e+02],
                [0.0, 0.0, 1.0]])

dist_coef = np.float64([2.4139278295843511e-01, -1.3984627843184050e+00 , 0, 0, 2.3861901454190999e+00])

def dist_to_camera(dist):
    tnew=np.arange(start=702,stop=140,step=-1)
    fvcubic=sp.interpolate.interp1d(t,v,kind='cubic')
    vcubic=fvcubic(tnew)
    return int(vcubic[int(702-dist)])



    #imgKeyPoints = cv2.drawKeypoints(red_mask, keypoints, np.array([]), (0,0,255), cv2.DRAW_MATCHES_FLAGS_DRAW_RICH_KEYPOINTS)
    #imgKeyPoints = cv2.drawKeypoints(blur_frame, keypoints, np.array([]), (0,0,255), cv2.DRAW_MATCHES_FLAGS_DRAW_RICH_KEYPOINTS)

    #font = cv2.FONT_HERSHEY_SIMPLEX
    #cv2.putText(red_mask,'1',(int(c_points[0,0]),int(c_points[0,1])), font, 4,(50,50,50),2,cv2.LINE_AA)

    retval, corners = cv2.findChessboardCorners(hsv_frame, (6,9), flags=cv2.CALIB_CB_FAST_CHECK)

    cv2.drawChessboardCorners(blur_frame, (6,9), corners, retval)

    cv2.imshow("Frame", blur_frame)

    #cv2.imshow("Red", red)

    #cv2.imshow("Keypoints", imgKeyPoints)

    key = cv2.waitKey(1)
    if key == 27:
        print("---------------------")
        #print(values)
        break
    elif key == 13:
        print(c_points)
        _ret, rvec, tvec = cv2.solvePnP(i_points, c_points, K, dist_coef)
        print(rvec)
        print(tvec)
        rotM = cv2.Rodrigues(rvec)[0]
        print(rotM)
        cameraPosition = -np.matrix(rotM).T * np.matrix(tvec)
        print(cameraPosition)
