#!/usr/bin/python
import cv2
import numpy as np

cap = cv2.VideoCapture("rtsp://192.168.1.171")

c_points = np.float32
i_points = np.float32([[0, 0, 0], [0, 130, 0], [130, 0, 0], [130, 130, 0]])

K = np.float64([[1.8196232063840237e+03, 0, 9.5950000000000000e+02],
                [0, 1.8196232063840237e+03, 5.3950000000000000e+02],
                [0.0, 0.0, 1.0]])

dist_coef = np.float64([2.4139278295843511e-01, -1.3984627843184050e+00 , 0, 0, 2.3861901454190999e+00])

while True:
    _, frame = cap.read()
    blur_frame = cv2.GaussianBlur(frame, (5,5), 1)
    hsv_frame = cv2.cvtColor(blur_frame, cv2.COLOR_BGR2HSV)

    retval, corners = cv2.findChessboardCorners(blur_frame, (6,9), flags=cv2.CALIB_CB_FAST_CHECK)

    if retval:
        r,g,b=cv2.split(blur_frame)
        criteria = (cv2.TermCriteria_EPS + cv2.TermCriteria_MAX_ITER, 30, 0.1)
        cv2.cornerSubPix(r, corners, (11,11), (-1,-1), criteria)

    cv2.drawChessboardCorners(blur_frame, (6,9), corners, retval)

    print(corners)

    cv2.imshow("Frame", blur_frame)

    key = cv2.waitKey(1)
    if key == 27:
        print("---------------------")
        print(corners[0])
        break
