#!C:/Python27/python.exe

import requests 
  
# api-endpoint 
URL = "http://192.168.1.202/open"
  

PARAMS = {} 
  
# sending get request and saving the response as response object 
r = requests.get(url = URL, params = PARAMS) 


