#!/usr/bin/python

import cv2
import time
import multiprocessing as mp
import numpy as np
import rospkg
import yaml
import thread

rospack = rospkg.RosPack()

class camera():

    def __init__(self,rtsp_url):        
        #load pipe for data transmittion to the process
        self.parent_conn, child_conn = mp.Pipe()
        #load process
        self.p = mp.Process(target=self.update, args=(child_conn,rtsp_url))        
        #start process
        self.p.daemon = True
        self.p.start()

    def end(self):
        #send closure request to process

        self.parent_conn.send(2)

    def update(self,conn,rtsp_url):
        #load cam into seperate process

        print("Cam Loading...")
        cap = cv2.VideoCapture(rtsp_url,cv2.CAP_FFMPEG)   
        print("Cam Loaded...")
        run = True

        while run:

            #grab frames from the buffer
            cap.grab()

            #recieve input data
            rec_dat = conn.recv()


            if rec_dat == 1:
                #if frame requested
                ret,frame = cap.read()
                conn.send(frame)

            elif rec_dat ==2:
                #if close requested
                cap.release()
                run = False

        print("Camera Connection Closed")        
        conn.close()

    def get_frame(self,resize=None):
        ###used to grab frames from the cam connection process

        ##[resize] param : % of size reduction or increase i.e 0.65 for 35% reduction  or 1.5 for a 50% increase

        #send request
        self.parent_conn.send(1)
        frame = self.parent_conn.recv()

        #reset request 
        self.parent_conn.send(0)

        #resize if needed
        if resize == None:            
            return frame
        else:
            return self.rescale_frame(frame,resize)

    def rescale_frame(self,frame, percent=65):

        return cv2.resize(frame,None,fx=percent,fy=percent) 

cam1 = camera("rtsp://192.168.1.105")
cam2 = camera("rtsp://192.168.1.171")

criteria = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 30, 0.001)

objp = np.zeros((6*9,3), np.float32)
objp[:,:2] = np.mgrid[0:9,0:6].T.reshape(-1,2)

objpoints = [] 

imgpoints1 = [] 
imgpoints2 = [] 

img_nb = 20

def findCBC1(img):
    global img_nb
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    ret, corners = cv2.findChessboardCorners(gray, (6,9), None)
    print("findCBC1")
    if ret == True:
        objpoints.append(objp)
        corners2 = cv2.cornerSubPix(gray,corners,(11,11),(-1,-1),criteria)
        imgpoints1.append(corners2)
        img_nb -= 1
        print(corners2)
        print("Remaining Images: " + str(img_nb))

def findCBC2(img):
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    ret, corners = cv2.findChessboardCorners(gray, (6,9), None)
    print("findCBC2")
    if ret == True:
        corners2 = cv2.cornerSubPix(gray,corners,(11,11),(-1,-1),criteria)
        imgpoints2.append(corners2)
        print(corners2)


while(1):
    img1 = cam1.get_frame(0.65)
    img2 = cam2.get_frame(0.65)

    cv2.imshow('img1', img1)
    cv2.imshow('img2', img2)

    key = cv2.waitKey(1)

    if key == 27:
        break
    elif (key == 10) and (img_nb > 0):
        thread.start_new_thread(findCBC1,(img1,))
        thread.start_new_thread(findCBC2,(img2,))
    elif(img_nb == 0):
        ret1, mtx1, dist1, rvecs1, tvecs1 = cv2.calibrateCamera(objpoints, imgpoints1, (1920,1080), None, None)

        data1 = {'camera_matrix': np.asarray(mtx1).tolist(),
                'dist_coeff': np.asarray(dist1).tolist()}

        with open(rospack.get_path('nsra_computer_vision') + "/config/calibration_matrix1.yaml", "w") as f1:
            yaml.dump(data1, f1)

        ret2, mtx2, dist2, rvecs2, tvecs2 = cv2.calibrateCamera(objpoints, imgpoints2, (1920,1080), None, None)

        data2 = {'camera_matrix': np.asarray(mtx2).tolist(),
                'dist_coeff': np.asarray(dist2).tolist()}

        with open(rospack.get_path('nsra_computer_vision') + "/config/calibration_matrix1.yaml", "w") as f2:
            yaml.dump(data2, f2)
        break
            
cv2.destroyAllWindows()     

cam.end()

