#!/usr/bin/python
import numpy as np
import cv2
from mpl_toolkits import mplot3d
import matplotlib.pyplot as plt
import rospy
from std_msgs.msg import String

fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')

x = np.array([10])
y = np.array([20])
z = np.array([3])

flag = False

def plot_callback(data):
    global x
    global y
    global z
    global flag
    xn, yn, zn = data.data.split("/")
    print(xn)
    print(yn)
    print(zn)
    x = np.append(x, xn)
    y = np.append(y, yn)
    z = np.append(z, zn)
    ax.scatter(x, y, z)
    flag = True

rospy.init_node('plot_3d_points')
rospy.Subscriber("3DPointCoords", String, plot_callback)

plt.show()
