#!/usr/bin/python
import numpy as np
from mpl_toolkits import mplot3d
import matplotlib.pyplot as plt
import rospy
from std_msgs.msg import String

fig = plt.figure()
ax = plt.axes(projection='3d')

def plot_callback(data):
    x, y, z = data.data.split("/")
    print(x)
    print(y)
    print(z)
    ax.scatter3D(x, y, z, c=z, cmap='Greens')

rospy.init_node('plot_3d_points')
rospy.Subscriber("3DPointCoords", String, plot_callback)

rospy.spin()