#!/usr/bin/python
import cv2
import numpy as np
import rospkg

rospack = rospkg.RosPack()

cap1 = cv2.VideoCapture("rtsp://192.168.1.171")
cap2 = cv2.VideoCapture("rtsp://192.168.1.102")

fs1 = cv2.FileStorage(rospack.get_path('nsra_computer_vision') + "/camera1_conf.xml", cv2.FILE_STORAGE_READ)
fs2 = cv2.FileStorage(rospack.get_path('nsra_computer_vision') + "/camera2_conf.xml", cv2.FILE_STORAGE_READ)

c_points = np.float32([[1269.7775,   450.22125],
                       [1275.9633,   501.22632],
                       [1282.4819,   553.8286 ],
                       [1289.4609,   608.8263 ],
                       [1296.682 ,   666.7097 ],
                       [1304.3273,   726.9574 ],
                       [1209.2323,   451.0076 ],
                       [1213.9106,   501.57715],
                       [1219.1492,   554.1556 ],
                       [1224.7256,   609.016  ],
                       [1230.3873,   666.7997 ],
                       [1236.3438,   726.9991 ],
                       [1148.5327,   451.59174],
                       [1152.3075,   501.69705],
                       [1156.288 ,   554.2279 ],
                       [1160.2096,   609.1209 ],
                       [1164.6307,   666.884  ],
                       [1168.9136,   727.0091 ],
                       [1088.7517,   452.37686],
                       [1090.734 ,   502.58194],
                       [1093.6362,   554.8394 ],
                       [1096.358 ,   609.455  ],
                       [1099.2709,   666.69995],
                       [1102.3958,   727.0539 ],
                       [1028.9832,   452.6434 ],
                       [1030.2454,   503.1015 ],
                       [1031.4948,   555.33734],
                       [1032.8146,   609.6909 ],
                       [1034.1716,   667.0106 ],
                       [1035.745 ,   726.6824 ],
                       [ 969.57355,  453.61362],
                       [ 969.53577,  503.59335],
                       [ 969.6311,   555.3115 ],
                       [ 969.5539,   609.994  ],
                       [ 969.5886,   667.214  ],
                       [ 969.6812,   726.9563 ],
                       [ 910.4853,   454.14642],
                       [ 909.37415,  504.13785],
                       [ 907.8849,   555.6694 ],
                       [ 906.5609,   610.48663],
                       [ 904.9799,   667.2879 ],
                       [ 903.4268,   727.2001 ],
                       [ 850.8979,   453.48752],
                       [ 848.5774,   504.37463],
                       [ 846.3176,   556.1188 ],
                       [ 843.232 ,   610.82056],
                       [ 840.39526,  667.6771 ],
                       [ 837.1548,   727.3801 ],
                       [ 791.55316,  453.53558],
                       [ 788.36646,  504.57272],
                       [ 784.35846,  556.81824],
                       [ 780.4502,   611.5713 ],
                       [ 775.78094,  668.07007],
                       [ 770.8579,   727.95135]])

i_points = np.float32([[0  ,  0 , 0],
                       [0  , 25 , 0],
                       [0  , 50 , 0],
                       [0  , 75 , 0],
                       [0  , 100, 0],
                       [0  , 125, 0],
                       [25 , 0  , 0],
                       [25 , 25 , 0],
                       [25 , 50 , 0],
                       [25 , 75 , 0],
                       [25 , 100, 0],
                       [25 , 125, 0],
                       [50 , 0  , 0],
                       [50 , 25 , 0],
                       [50 , 50 , 0],
                       [50 , 75 , 0],
                       [50 , 100, 0],
                       [50 , 125, 0],
                       [75 , 0  , 0],
                       [75 , 25 , 0],
                       [75 , 50 , 0],
                       [75 , 75 , 0],
                       [75 , 100, 0],
                       [75 , 125, 0],
                       [100, 0  , 0],
                       [100, 25 , 0],
                       [100, 50 , 0],
                       [100, 75 , 0],
                       [100, 100, 0],
                       [100, 125, 0],
                       [125, 0  , 0],
                       [125, 25 , 0],
                       [125, 50 , 0],
                       [125, 75 , 0],
                       [125, 100, 0],
                       [125, 125, 0],
                       [150, 0  , 0],
                       [150, 25 , 0],
                       [150, 50 , 0],
                       [150, 75 , 0],
                       [150, 100, 0],
                       [150, 125, 0],
                       [175, 0  , 0],
                       [175, 25 , 0],
                       [175, 50 , 0],
                       [175, 75 , 0],
                       [175, 100, 0],
                       [175, 125, 0],
                       [200, 0  , 0],
                       [200, 25 , 0],
                       [200, 50 , 0],
                       [200, 75 , 0],
                       [200, 100, 0],
                       [200, 125, 0]])

K1 = fs1.getNode("Camera_Matrix").mat()
dist_coef1 = fs1.getNode("Distortion_Coefficients").mat()

print(K1)

K2 = fs2.getNode("Camera_Matrix").mat()
dist_coef2 = fs2.getNode("Distortion_Coefficients").mat()

while True:
    _, frame1 = cap1.read()
    _, frame2 = cap2.read()

    blur_frame1 = cv2.GaussianBlur(frame1, (5,5), 1)
    hsv_frame1 = cv2.cvtColor(blur_frame1, cv2.COLOR_BGR2HSV)

    blur_frame2 = cv2.GaussianBlur(frame2, (5,5), 1)
    hsv_frame2 = cv2.cvtColor(blur_frame2, cv2.COLOR_BGR2HSV)

    retval1, corners1 = cv2.findChessboardCorners(blur_frame1, (6,9), flags=cv2.CALIB_CB_FAST_CHECK)
    retval2, corners2 = cv2.findChessboardCorners(blur_frame2, (6,9), flags=cv2.CALIB_CB_FAST_CHECK)

    if retval1:
        r,g,b=cv2.split(blur_frame1)
        criteria = (cv2.TermCriteria_EPS + cv2.TermCriteria_MAX_ITER, 30, 0.1)
        cv2.cornerSubPix(r, corners1, (11,11), (-1,-1), criteria)

    if retval2:
        r,g,b=cv2.split(blur_frame2)
        criteria = (cv2.TermCriteria_EPS + cv2.TermCriteria_MAX_ITER, 30, 0.1)
        cv2.cornerSubPix(r, corners2, (11,11), (-1,-1), criteria)

    cv2.drawChessboardCorners(blur_frame1, (6,9), corners1, retval1)
    cv2.drawChessboardCorners(blur_frame2, (6,9), corners2, retval2)

    #print(corners)

    cv2.imshow("Frame1", blur_frame1)
    cv2.imshow("Frame2", blur_frame2)

    key = cv2.waitKey(1)
    if key == 27:
        print("Callibration Aborted!")
        break
    elif key == 13:
        print("test")

#_ret, rvec, tvec = cv2.solvePnP(i_points, c_points, K, dist_coef)
#rotM = cv2.Rodrigues(rvec)[0]
#cameraPosition = -np.matrix(rotM).T * np.matrix(tvec)
#cv2.stereoCalibrate(i_points, c_points)